services:
  speech2text:
    build: .
    image: kavitha245p/speech2text:cpu
    container_name: stt_container
    volumes:
      - ./input_videos:/app/input_videos
      - ./output:/app/output
      - ./config.json:/app/config.json

    # Default command (CLI-only)
    command: ["python", "trascrizione.py", "--no-gui"]
    stdin_open: true
    tty: true
